regress pay_satisfaction real_wage real_wage_sq log_real_wage m5_res


regress pay_satisfaction real_wage real_wage_sq log_real_wage m1_res
regress pay_satisfaction real_wage real_wage_sq log_real_wage m2_res
regress pay_satisfaction real_wage real_wage_sq log_real_wage m3_res
regress pay_satisfaction real_wage real_wage_sq log_real_wage m4_res
regress pay_satisfaction real_wage real_wage_sq log_real_wage m6_res


regress pay_satisfaction real_wage real_wage_sq log_real_wage m5_res experience experience_sq edu_uni edu_diploma children_1 children_2 children_3 children_4_plus health_poor birth_eng birth_neng married_yes married_sep urban_no state_VIC state_WA state_QLD state_SA state_NT state_TAS state_ACT shiftwork_yes parttime long_hours casual union_yes ind_wholesale ind_finance ind_education ind_mine ind_retail ind_housing ind_health ind_manufact ind_accomo_food ind_prof_sci_technical ind_arts_rec ind_utilities ind_logistics ind_admin ind_other_unknown ind_construct ind_it ind_public_admin occ_tech_trade occ_clerical_admin occ_machinery occ_prof occ_community_personal_service occ_sales occ_labourer
